name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Update submodules
      run: git submodule update --init
    - name: Build contract
      run: make all-via-docker
    - name: Build exec scripts
      run: make -f tests/taproot_lock/exec_script.Makefile all-via-docker
    - name: Run taproot lock tests
      run: cd tests/taproot_lock_rust && cargo test
